export {
  type Doc,
  COLORS,
  PAGE,
  registerPdfFont,
  type SupportedLocale,
  resolveLocale,
  getLocaleString,
  formatDate,
  formatDateShort,
  getLabels,
  ensureSpace,
  drawSectionHeader,
  drawKeyValue,
  drawParagraph,
  drawBullet,
  drawTableRow,
  addPageNumbers,
} from '../../shared/pdf/pdf-shared';
