/**
 * Centralised audit action enum — single source of truth.
 * Every call to auditService.log() MUST use a value from this enum.
 */
export enum AuditAction {
  // ── Auth ────────────────────────────────────────────
  USER_REGISTERED = 'USER_REGISTERED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_LOGOUT_ALL = 'USER_LOGOUT_ALL',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  PHONE_VERIFIED = 'PHONE_VERIFIED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',

  // ── Security ───────────────────────────────────────
  USER_BANNED = 'USER_BANNED',
  USER_UNBANNED = 'USER_UNBANNED',
  IP_BLACKLISTED = 'IP_BLACKLISTED',
  SUSPICIOUS_SCORE_INCREASED = 'SUSPICIOUS_SCORE_INCREASED',

  // ── Consent / GDPR ────────────────────────────────
  CONSENT_GRANTED = 'CONSENT_GRANTED',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  USER_SELF_DELETED = 'USER_SELF_DELETED',
  USER_DATA_EXPORTED = 'USER_DATA_EXPORTED',

  // ── Admin ──────────────────────────────────────────
  ADMIN_USER_UPDATED = 'ADMIN_USER_UPDATED',
  ADMIN_MASTER_UPDATED = 'ADMIN_MASTER_UPDATED',

  // ── Verification ───────────────────────────────────
  VERIFICATION_SUBMITTED = 'VERIFICATION_SUBMITTED',
  VERIFICATION_REVIEWED = 'VERIFICATION_REVIEWED',
  VERIFICATION_DOCUMENTS_PURGED = 'VERIFICATION_DOCUMENTS_PURGED',

  // ── Tariffs & Payments ─────────────────────────────
  TARIFF_CREATED = 'TARIFF_CREATED',
  TARIFF_UPDATED = 'TARIFF_UPDATED',
  TARIFF_DELETED = 'TARIFF_DELETED',
  FREE_PLAN_CLAIMED = 'FREE_PLAN_CLAIMED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  TARIFF_UPGRADE_CONFIRMED = 'TARIFF_UPGRADE_CONFIRMED',
  TARIFF_UPGRADE_CANCELLED = 'TARIFF_UPGRADE_CANCELLED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
}

/** Actions that trigger a WARN-level security log line. */
export const SECURITY_ACTIONS: readonly AuditAction[] = [
  AuditAction.USER_BANNED,
  AuditAction.USER_UNBANNED,
  AuditAction.IP_BLACKLISTED,
  AuditAction.SUSPICIOUS_SCORE_INCREASED,
  AuditAction.LOGIN_FAILED,
  AuditAction.PHONE_VERIFIED,
];
