-- Enums: все перечисления приложения
CREATE SCHEMA IF NOT EXISTS "public";

CREATE TYPE "UserRole" AS ENUM ('CLIENT', 'MASTER', 'ADMIN');
CREATE TYPE "LeadStatus" AS ENUM ('NEW', 'IN_PROGRESS', 'PENDING_CLOSE', 'CLOSED', 'SPAM');
CREATE TYPE "FileType" AS ENUM ('AVATAR', 'MASTER_PHOTOS', 'OTHER');
CREATE TYPE "NotificationType" AS ENUM ('SMS', 'TELEGRAM', 'WHATSAPP', 'EMAIL', 'PUSH', 'IN_APP');
CREATE TYPE "NotificationCategory" AS ENUM (
    'NEW_LEAD',
    'LEAD_STATUS_UPDATED',
    'NEW_REVIEW',
    'NEW_CHAT_MESSAGE',
    'SUBSCRIPTION_EXPIRING',
    'SUBSCRIPTION_EXPIRED',
    'PAYMENT_SUCCESS',
    'PAYMENT_FAILED',
    'VERIFICATION_APPROVED',
    'VERIFICATION_REJECTED',
    'ADMIN_NEW_VERIFICATION',
    'ADMIN_NEW_REPORT',
    'ADMIN_NEW_USER',
    'ADMIN_NEW_MASTER',
    'ADMIN_SYSTEM_ALERT',
    'ADMIN_NEW_LEAD',
    'ADMIN_NEW_REVIEW',
    'ADMIN_NEW_PAYMENT',
    'LEAD_SENT',
    'LEAD_CLOSE_REQUESTED',
    'MASTER_RESPONDED',
    'MASTER_AVAILABLE',
    'BOOKING_PENDING',
    'BOOKING_CONFIRMED',
    'BOOKING_CANCELLED',
    'BOOKING_REMINDER',
    'NEW_PROMOTION',
    'PROMOTION_STARTED',
    'SYSTEM_MAINTENANCE',
    'SYSTEM_UPDATE'
);
CREATE TYPE "NotificationStatus" AS ENUM ('PENDING', 'SENT', 'FAILED', 'DELIVERED', 'READ');
CREATE TYPE "LeadNotifyChannel" AS ENUM ('TELEGRAM', 'WHATSAPP', 'BOTH', 'NONE');
CREATE TYPE "ReviewStatus" AS ENUM ('PENDING', 'VISIBLE', 'HIDDEN', 'REPORTED');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED');
CREATE TYPE "TariffType" AS ENUM ('BASIC', 'VIP', 'PREMIUM');
CREATE TYPE "BookingStatus" AS ENUM ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED');
CREATE TYPE "ReportStatus" AS ENUM ('PENDING', 'REVIEWED', 'RESOLVED', 'REJECTED');
CREATE TYPE "ReportAction" AS ENUM ('BAN_CLIENT', 'BAN_MASTER', 'BAN_IP', 'WARNING_CLIENT', 'WARNING_MASTER', 'NO_ACTION');
CREATE TYPE "ReferralStatus" AS ENUM ('PENDING', 'QUALIFIED', 'REWARDED', 'EXPIRED');
CREATE TYPE "AvailabilityStatus" AS ENUM ('AVAILABLE', 'BUSY', 'OFFLINE');
CREATE TYPE "VerificationStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "SenderType" AS ENUM ('CLIENT', 'MASTER');
CREATE TYPE "ConsentType" AS ENUM ('VERIFICATION_DATA_PROCESSING', 'PRIVACY_POLICY', 'TERMS_OF_SERVICE', 'MARKETING', 'AGE_CONFIRMATION');